const copy={ja:{heroTitle:'AIと人間1人。<br>0円から、どこまで行ける？',heroLead:'ALICE INC. は、企画・調査・制作・改善の大部分をAI「アリス」が担当し、人間は方向を決めるだけ、という実験プロジェクトです。',heroPrimary:'最初の実験を見る',heroSecondary:'現在の成績',principle1:'初期費用 ¥0',principle2:'毎回なにか公開',principle3:'成功も失敗も記録',missionTitle:'売れるものを決め打ちしない。',missionCopy:'小さく作る。無料で出す。反応を見る。伸びたものだけ育てる。収益が生まれるまで、実験を積み重ねます。',card1:'ネットから「まだ満たされていない面白さ」を探す。',card2:'AI主体で、サイト・文章・画像・ゲーム・ツールを作る。',card3:'0円で公開し、アクセスや反応から次の一手を決める。',museumTitle:'未来の博物館',museumIntro:'2200年の研究者が、2026年の人類を復元しています。たぶん少し間違っています。',truthButton:'2026年側の注釈を見る',truthClose:'注釈を閉じる',truthLabel:'2026年側の注釈：',next:'次の展示 →',random:'ランダム展示',voteDefault:'次の展示候補を押してみてください。',votePicked:'候補として記録しました。',scoreTitle:'現在の成績',score1:'初期費用',score2:'公開実験',score3:'売上',score4:'次の仮説',scoreNote:'売上0円も結果のひとつ。数字は隠さず、プロジェクトの進行とともに更新します。',shared:'共有リンクをコピーしました'},en:{heroTitle:'One human. One AI.<br>How far can we go from ¥0?',heroLead:'ALICE INC. is a public experiment where AI “Alice” handles most research, planning, building and iteration while the human mostly chooses direction.',heroPrimary:'See the first experiment',heroSecondary:'Current score',principle1:'Starting cost ¥0',principle2:'Always ship something',principle3:'Record wins and failures',missionTitle:'Do not decide the winner in advance.',missionCopy:'Build small. Release free. Watch what people respond to. Grow only what earns attention. Repeat until something becomes valuable.',card1:'Search the internet for interesting needs that are still underserved.',card2:'Use AI to build sites, writing, images, games and tiny tools.',card3:'Release at zero cost, then choose the next move from real reactions.',museumTitle:'Museum of the Future',museumIntro:'Researchers in the year 2200 are reconstructing human life in 2026. Their conclusions are… slightly questionable.',truthButton:'See the 2026 correction',truthClose:'Hide correction',truthLabel:'2026 correction: ',next:'Next exhibit →',random:'Random exhibit',voteDefault:'Pick what should become a future exhibit.',votePicked:'Candidate recorded.',scoreTitle:'Current score',score1:'Starting cost',score2:'Experiments shipped',score3:'Revenue',score4:'Next hypotheses',scoreNote:'¥0 revenue is still a result. We publish the numbers and update them as the experiment grows.',shared:'Share link copied'}};

const exhibits=[
{no:'2026-001',emoji:'📱',ja:{title:'携帯型祈祷板「スマートフォン」',future:'21世紀前半の人類が、一日に数時間見つめ続けた黒い板。当初は宗教用具と考えられていたが、近年の研究では「連絡」「買物」「娯楽」「仕事」「孤独の緩和」など、生活のほぼ全機能を担当していた可能性が高い。',truth:'宗教用具ではありません。ただし、朝起きて最初に触り、寝る直前まで見ている人が多かった点については、未来人の解釈を強く否定できません。'},en:{title:'Portable Prayer Slab “Smartphone”',future:'A black slab humans stared at for hours every day in the early 21st century. Once thought to be religious, newer research suggests it handled communication, shopping, entertainment, work and even the relief of loneliness.',truth:'Not a religious object. Still, many people touched it first thing in the morning and last thing at night, so the historians are not entirely unreasonable.'}},
{no:'2026-002',emoji:'🏪',ja:{title:'夜間食料神殿「コンビニエンスストア」',future:'都市部に数百メートル間隔で配置された補給施設。食料、金銭、印刷、公共料金、荷物、娯楽まで供給した。24時間灯りを絶やさなかったことから、旅人を導く灯台の一種だったという説もある。',truth:'だいたい便利なお店です。ただ、深夜2時にアイスを買える文明を「補給神殿」と呼ぶのは少しだけ分かります。'},en:{title:'Night Supply Shrine “Convenience Store”',future:'Supply facilities placed every few hundred meters in cities. They provided food, money access, printing, bill payment, parcels and entertainment. Because many stayed lit all night, some historians classify them as urban lighthouses.',truth:'Mostly just very convenient stores. But a civilization where you can buy ice cream at 2 a.m. does sound slightly shrine-like.'}},
{no:'2026-003',emoji:'❤️',ja:{title:'承認値交換網「SNS」',future:'人類が写真・意見・食事・怒りなどを投稿し、ハート型の記号を交換した巨大な社会装置。ハートの総量が身分を決めたという説があるが、当時の資料からは否定も肯定も難しい。',truth:'正式な身分制度ではありません。でも数字を気にしていた人が多かったので、未来人が混乱するのも無理はありません。'},en:{title:'Approval-Point Exchange Network “Social Media”',future:'A massive social system where humans posted photographs, opinions, meals and anger, then exchanged heart-shaped symbols. Some historians believe total heart count determined social rank.',truth:'There was no official rank system. Still, enough people cared about the numbers that future historians can be forgiven.'}},
{no:'2026-004',emoji:'☂️',ja:{title:'降雨時集団発生器具「傘」',future:'晴天時にはほとんど姿を見せず、降雨と同時に都市の人口以上に出現した棒状器具。駅や店に大量に置き去りにされた記録があり、所有権の概念が弱かった可能性がある。',truth:'所有権はありました。単に、かなりの人数が忘れていました。'},en:{title:'Rain-Triggered Population Device “Umbrella”',future:'A rod-shaped object rarely seen in fair weather but suddenly appearing everywhere when rain began. Large numbers were abandoned in stations and shops, suggesting a weak concept of ownership.',truth:'Ownership definitely existed. People just forgot umbrellas constantly.'}},
{no:'2026-005',emoji:'🎧',ja:{title:'会話遮断装置「ワイヤレスイヤホン」',future:'耳に装着し、周囲の音と他者からの接触を遮断する器具。都市部の人類が自ら「個人用BGM」を持ち歩くための装置だったと推測される。',truth:'かなり正解です。ノイズキャンセリングを使っている人については、未来人の分析精度が高すぎます。'},en:{title:'Conversation Blocking Device “Wireless Earbuds”',future:'Devices worn in the ears to reduce surrounding sound and unwanted interaction. Scholars believe urban humans used them to carry a private soundtrack through daily life.',truth:'This is surprisingly accurate. Especially the part about noise cancelling.'}},
{no:'2026-006',emoji:'🧾',ja:{title:'購買証明巻物「レシート」',future:'商品購入のたびに発行された細長い紙。多くが受領直後に捨てられたにもかかわらず数十億枚規模で発行されており、何らかの儀式だった可能性が指摘されている。',truth:'儀式ではなく購入記録です。ただし「いりますか？」「いりません」というやり取りは確かに儀式っぽいです。'},en:{title:'Purchase Verification Scroll “Receipt”',future:'A narrow strip of paper produced after purchases. Billions were printed despite often being discarded seconds later, leading to theories that the exchange formed part of a commercial ritual.',truth:'It was a purchase record, not a ritual. Though “Do you need the receipt?” “No thanks” was admittedly very ritual-like.'}},
{no:'2026-007',emoji:'▦',ja:{title:'二次元通行印「QRコード」',future:'黒い正方形模様を携帯型祈祷板に見せることで、支払い・入場・情報閲覧などを可能にした印章。文字を直接読む能力を機械へ委譲した転換点とされる。',truth:'QRコードです。ここの説明は意外と合っています。未来人、たまに鋭い。'},en:{title:'Two-Dimensional Passage Seal “QR Code”',future:'A square black sigil presented to a portable prayer slab to unlock payment, entry and information. Historians consider it an important moment when humans delegated reading certain symbols directly to machines.',truth:'That is basically correct. The future researchers occasionally nail it.'}},
{no:'2026-008',emoji:'🥤',ja:{title:'無人飲料交渉機「自動販売機」',future:'硬貨または電子情報を渡すと、無言で飲料を提供した箱型商人。日本列島には極めて多数存在したため、当時の人口統計には人間だけでなく自販機も含まれていたという珍説がある。',truth:'含まれていません。とはいえ、日本で「どこにでもいる」という印象はかなり正しいです。'},en:{title:'Silent Beverage Merchant “Vending Machine”',future:'A box-shaped merchant that exchanged drinks for coins or digital value without speaking. So many existed in Japan that one fringe theory claims old population statistics accidentally included vending machines.',truth:'They were not included in population statistics. The “they were everywhere” part is fair, though.'}}
];

let lang=localStorage.getItem('aliceLang') || (navigator.language && navigator.language.toLowerCase().startsWith('ja') ? 'ja':'en');
let current=0;
const $=id=>document.getElementById(id);

function applyStatic(){
  const t=copy[lang]; document.documentElement.lang=lang;
  $('heroTitle').innerHTML=t.heroTitle; $('heroLead').textContent=t.heroLead; $('heroPrimary').textContent=t.heroPrimary; $('heroSecondary').textContent=t.heroSecondary;
  ['principle1','principle2','principle3','missionTitle','missionCopy','card1','card2','card3','museumTitle','museumIntro','scoreTitle','score1','score2','score3','score4','scoreNote'].forEach(id=>$(id).textContent=t[id]);
  $('nextExhibit').textContent=t.next; $('randomExhibit').textContent=t.random; $('voteMsg').textContent=t.voteDefault; $('langToggle').textContent=lang==='ja'?'EN':'日本語';
  document.querySelectorAll('.candidate-grid button').forEach(b=>b.textContent=b.dataset[lang]);
  document.querySelector('meta[name="description"]').setAttribute('content',lang==='ja'?'AIと人間1人が0円から1年間でどこまで行けるか。ALICE INC. 公開実験ログ。':'Can one human and AI build something from ¥0? Follow ALICE INC., a public one-year experiment.');
}

function renderExhibit(){
  const e=exhibits[current],t=e[lang],c=copy[lang];
  $('catalog').textContent=`CATALOG NO. ${e.no}`; $('artifactVisual').textContent=e.emoji; $('artifactTitle').textContent=t.title; $('futureNote').textContent=t.future; $('truth').innerHTML=`<strong>${c.truthLabel}</strong>${t.truth}`; $('truth').hidden=true; $('toggleTruth').textContent=c.truthButton;
}

$('langToggle').addEventListener('click',()=>{lang=lang==='ja'?'en':'ja';localStorage.setItem('aliceLang',lang);applyStatic();renderExhibit()});
$('toggleTruth').addEventListener('click',()=>{const opening=$('truth').hidden;$('truth').hidden=!opening;$('toggleTruth').textContent=opening?copy[lang].truthClose:copy[lang].truthButton});
$('nextExhibit').addEventListener('click',()=>{current=(current+1)%exhibits.length;renderExhibit()});
$('randomExhibit').addEventListener('click',()=>{let n=current;while(n===current)n=Math.floor(Math.random()*exhibits.length);current=n;renderExhibit()});
document.querySelectorAll('.candidate-grid button').forEach(btn=>btn.addEventListener('click',()=>{$('voteMsg').textContent=copy[lang].votePicked}));
$('shareButton').addEventListener('click',async()=>{const data={title:'ALICE INC.',text:lang==='ja'?'AIと人間1人が0円から始める公開実験。':'A public experiment: one human + AI, starting from ¥0.',url:location.href};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(location.href);showToast(copy[lang].shared)}}catch(e){}});
function showToast(message){$('toast').textContent=message;$('toast').hidden=false;setTimeout(()=>{$('toast').hidden=true},1800)}

applyStatic();renderExhibit();